// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDda2BnJefJWZ150_ZGmR7Tp4QwySDW80M',
    appId: '1:472349345875:web:04e08c42c7b8904cb35ea6',
    messagingSenderId: '472349345875',
    projectId: 'youtune-c98ba',
    authDomain: 'youtune-c98ba.firebaseapp.com',
    storageBucket: 'youtune-c98ba.appspot.com',
    measurementId: 'G-VJGJ3X5L0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2FTjXifuG4YmgBDymwERncSPoXHNRWoA',
    appId: '1:472349345875:android:0d939d0e680ef476b35ea6',
    messagingSenderId: '472349345875',
    projectId: 'youtune-c98ba',
    storageBucket: 'youtune-c98ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlFrc_ynWp2ssf32rmyddf-5LmGnCg1RU',
    appId: '1:472349345875:ios:7e8f8a1d10e44699b35ea6',
    messagingSenderId: '472349345875',
    projectId: 'youtune-c98ba',
    storageBucket: 'youtune-c98ba.appspot.com',
    iosBundleId: 'com.example.youtune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlFrc_ynWp2ssf32rmyddf-5LmGnCg1RU',
    appId: '1:472349345875:ios:851e22916ac0cc91b35ea6',
    messagingSenderId: '472349345875',
    projectId: 'youtune-c98ba',
    storageBucket: 'youtune-c98ba.appspot.com',
    iosBundleId: 'com.example.youtune.RunnerTests',
  );
}
